### ISSUE TITLE
hello！

### ISSUE THREAD

**Issue by SoulProficiency** [aosses-tue/fluctuation-strength-TUe#1]
can we calculate the audio Fluctuation strength with this code?
i'm reading <psychoacoustics : facts and models> and i've not found the code to calculate the signal Fluctuation strength

**Comment by uglyrocks** [comment]
Hi @SoulProficiency, of course you can compute the Fluctuation strength, that's what's this repository for.
Download the repository, then: 
**(Step 1)** run the script [FS_TUe_start.m](https://github.com/aosses-tue/fluctuation-strength-TUe/blob/master/FS_TUe_start.m)
**(Step 2)** run the script [demo_osses2016a.m](https://github.com/aosses-tue/fluctuation-strength-TUe/blob/master/demos/demo_osses2016a.m)

In this latter script you can see how the main script of fluctuation strength (FluctuationStrength_TUe) is used to process wave files. Make sure that the sounds are properly calibrated, and please have a careful look at the paper related to this code and at other files of this repository. I am happy to help further, but I don't always have the time to respond (timely) in such detail to new requests. 

Best regards,
Alejandro

**Comment by SoulProficiency** [comment]
thanks!
